# Generated by Django 5.0.4 on 2024-05-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_delete_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Product'},
        ),
    ]
